#!/usr/bin/env bash
# Mirror skill/ assets + references into site/brand/, then rebuild the downloadable skill zip.
# Run from anywhere:  bash scripts/sync.sh
#
# Why: site/brand/ is a PUBLIC MIRROR of the skill's assets so the website and the skill stay
# identical. The design source of truth is skill/assets/tokens/. There is no bundler.
set -euo pipefail
cd "$(dirname "$0")/.."            # -> repo root (brandkit/)

# 0. Generate a flattened, self-contained stylesheet (tokens + components, no @import).
#    Use for single-file / offline pages (one <link> or inlined <style>, no external CSS deps).
#    It is mirrored with the other tokens AND copied to site/brand.css so the short, guessable
#    URL /zknationbrand/brand.css resolves to a working sheet (the canonical link stays
#    /brand/tokens/brand.css). Regenerated here so it can never drift from the source.
INLINE="skill/assets/tokens/brand.inline.css"
{
  echo "/* brand.inline.css — GENERATED by scripts/sync.sh; do not edit by hand."
  echo "   Flattened & self-contained: tokens.css + brand.css with the @import inlined, so it works"
  echo "   as a single <link>/<style> with no external CSS dependency. The signature CTA arrow is an"
  echo "   inline data-URI, so even buttons need no asset fetch. Fonts still degrade to Inter/system"
  echo "   unless you also add fonts-demo.css (free look-alikes: Archivo + Space Mono) or your own"
  echo "   licensed @font-face. Source of truth: tokens.css + brand.css. */"
  cat skill/assets/tokens/tokens.css
  echo
  grep -v '@import "\./tokens\.css";' skill/assets/tokens/brand.css
} > "$INLINE"

# 0b. Regenerate the asset manifest from the REAL tree. It had drifted badly (listed 12 non-shipped
#     licensed font binaries and flag SVGs that don't exist, and omitted the ascii fields), so an agent
#     trusting it would write @font-face/<img> rules that 404. Generating it here keeps it truthful.
{
  echo "# Asset Manifest"
  echo
  echo "GENERATED by scripts/sync.sh from the real asset tree — do not edit by hand. Paths relative to \`skill/\`."
  echo "Commercial fonts (ES Allianz, Avenue Mono) are intentionally NOT bundled (git-ignored; see"
  echo "\`assets/fonts/README.md\` and \`references/font-licensing.md\`), so no font binaries appear below."
  echo
  ( cd skill && find assets -type d | sort | while read -r d; do
      fs=$(find "$d" -maxdepth 1 -type f ! -name '.DS_Store' ! -name 'MANIFEST.md' | sort)
      [ -z "$fs" ] && continue
      echo "## $d"
      for f in $fs; do echo "- \`$f\`"; done
      echo
    done )
} > skill/assets/MANIFEST.md

# 1. Mirror tokens, artwork, and references (NOT fonts — those are licensed, managed separately).
for d in tokens logos icons flags ascii; do
  rm -rf "site/brand/$d"
  cp -R "skill/assets/$d" "site/brand/$d"
done
rm -rf site/brand/references
cp -R skill/references site/brand/references

# 1b. Also serve the flattened sheet at the guessable root URL: /zknationbrand/brand.css
cp "$INLINE" site/brand.css

# 2. Licensed showcase fonts: refresh from the local-only licensed copy if present.
#    (ES Allianz + Avenue Mono are commercial; they are NOT in git. The site serves them
#     because the Association is licensed. See skill/references/font-licensing.md.)
if [ -d "_licensed-fonts-DO-NOT-REDISTRIBUTE" ]; then
  mkdir -p site/brand/fonts
  cp _licensed-fonts-DO-NOT-REDISTRIBUTE/*.woff2 _licensed-fonts-DO-NOT-REDISTRIBUTE/*.woff site/brand/fonts/ 2>/dev/null || true
fi

# 3. Rebuild the downloadable, license-clean skill zip.
find . -name .DS_Store -delete 2>/dev/null || true
rm -f site/zk-nation-brand-skill.zip
( zip -r -q site/zk-nation-brand-skill.zip skill -x '*.DS_Store' )

echo "✓ Synced skill/ -> site/brand/ and rebuilt site/zk-nation-brand-skill.zip"
echo "  Next: verify (Playwright), publish from site/ via here.now, commit, push (as rafathebuilder-ZK)."
